### ISSUE TITLE
TLAPM Pb

### ISSUE THREAD

**Issue by FilaliM** [tlaplus/tlapm#44] opened 2021-07-06 12:55 UTC
when compiling the following module:
------------------------------- MODULE Flat_0 -------------------------------
EXTENDS Naturals

LEMMA FLAT_R0 ==
  ASSUME NEW P(_)
  PROVE ((\A x1 \in Nat: \A x2 \in Nat: P(<<x1,x2>>))
                        =>
         (\A <<st1,st2>> \in (Nat \X Nat) : P(<<st1,st2>>)) 
        )
  OBVIOUS
=============================================================================
\* Modification History
\* Last modified Tue Jul 06 14:34:54 CEST 2021 by filali
\* Created Tue Jul 06 14:34:22 CEST 2021 by filali

I get the following report:
Oops, this seems to be a bug in TLAPM.
Please give feedback to developers.

 Failure("Module.Parser.parse_file")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from M_save.clocking in file "m_save.ml", line 25, characters 16-20
Called from Tlapm.read_new_modules.(fun) in file "tlapm.ml", line 455, characters 8-112
Called from Stdlib__list.fold_left in file "list.ml", line 121, characters 24-34
Called from Tlapm.main in file "tlapm.ml", line 486, characters 20-43
Called from Tlapm.init in file "tlapm.ml", line 513, characters 8-33

version == "1.5.0"
built_with == "OCaml 4.11.1"
tlapm_executable == "/Users/filali/Documents/GitHub/tlapm/bin/tlapm"
max_threads == 8
library_path == "/Users/filali/Documents/GitHub/tlapm/lib/tlaps"
search_path == << "/usr/local/lib/tlaps/"
                , "/Users/filali/Documents/GitHub/tlapm/lib/tlaps" >>
zenon == "PATH='/usr/bin:/bin:/usr/sbin:/sbin:/Users/filali/Documents/GitHub/tlapm/bin:/Users/filali/Documents/GitHub/tlapm/lib/tlaps/bin'; zenon -p0 -x tla -oisar -max-time 1d \"$file\""
zenon version == "zenon version 0.8.4 [a268] 2017-11-14"
flatten_obligations == TRUE
normalize == TRUE

----
Please give feedback to developers.

 Failure("Module.Parser.parse_file")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from M_save.clocking in file "m_save.ml", line 25, characters 16-20
Called from Tlapm.read_new_modules.(fun) in file "tlapm.ml", line 455, characters 8-112
Called from Stdlib__list.fold_left in file "list.ml", line 121, characters 24-34
Called from Tlapm.main in file "tlapm.ml", line 486, characters 20-43
Called from Tlapm.init in file "tlapm.ml", line 513, characters 8-33

version == "1.5.0"
built_with == "OCaml 4.11.1"
tlapm_executable == "/Users/filali/Documents/GitHub/tlapm/bin/tlapm"
max_threads == 8
library_path == "/Users/filali/Documents/GitHub/tlapm/lib/tlaps"
search_path == << "/usr/local/lib/tlaps/"
                , "/Users/filali/Documents/GitHub/tlapm/lib/tlaps" >>
zenon == "PATH='/usr/bin:/bin:/usr/sbin:/sbin:/Users/filali/Documents/GitHub/tlapm/bin:/Users/filali/Documents/GitHub/tlapm/lib/tlaps/bin'; zenon -p0 -x tla -oisar -max-time 1d \"$file\""
zenon version == "zenon version 0.8.4 [a268] 2017-11-14"
flatten_obligations == TRUE
normalize == TRUE
@!!END

**Comment by muenchnerkindl** [comment] 2021-07-06 15:14
This is essentially a duplicate of issue #11. It should be fixed in the next release. For the moment, you have to write

LEMMA FLAT_R0 ==
ASSUME NEW P(_)
PROVE ((\A x1 \in Nat: \A x2 \in Nat: P(<<x1,x2>>))
=>
(\A st \in (Nat \X Nat) : P(<<st[1],st[2]>>))
)
OBVIOUS

**Closed by muenchnerkindl** 2021-07-06 15:14 UTC
